/// @description  Initialize

// properties
_ex_cameras           = -1;
_ex_camera_debug_mode = false;
_ex_camera_version    = "1.6.0";
_ex_camera_count      = 0;
_suspended            = false;

// extension database
enum _ex_camera {
    _name,
    _view,
    _width,
    _height,
    _bound_x,
    _bound_y,
    _bound_width,
    _bound_height,
    _fade_start,
    _fade_end,
    _fade_tween_position,
    _fade_tween_duration,
    _fade_tween_easing,
    _fade_color,
    _fade_blend,
    _fade_alpha,
    _fade_draw_target,
    _flash_start,
    _flash_end,
    _flash_tween_position,
    _flash_tween_duration,
    _flash_tween_easing,
    _flash_color,
    _flash_alpha,
    _flash_blend,
    _flash_draw_target,
    _shake_start,
    _shake_end,
    _shake_tween_duration,
    _shake_tween_position,
    _shake_tween_easing,
    _shake_power_x,
    _shake_power_y,
    _shake_power_angle,
    _zoom_start_scale,
    _zoom_end_scale,
    _zoom_tween_duration,
    _zoom_tween_easing,
    _zoom_tween_position,
    _zoom_scale,
    _zoom_offset_x,
    _zoom_offset_y,
    _zoom_start_x,
    _zoom_start_y,
    _zoom_end_x,
    _zoom_end_y,
    _tilt_angle,
    _tilt_start,
    _tilt_end,
    _tilt_tween_duration,
    _tilt_tween_easing,
    _tilt_tween_position,
    _scroll_start_x,
    _scroll_start_y,
    _scroll_end_x,
    _scroll_end_y,
    _scroll_x,
    _scroll_y,
    _scroll_tween_duration,
    _scroll_tween_easing,
    _scroll_tween_position,
    _resize_tween_position,
    _resize_tween_duration,
    _resize_tween_easing,
    _resize_start_x,
    _resize_start_y,
    _resize_end_x,
    _resize_end_y,
    _resize_start_width,
    _resize_start_height,
    _resize_end_width,
    _resize_end_height,
    _resize_oncomplete,
    _resize_oncomplete_arguments,
    _fade_oncomplete,
    _fade_oncomplete_arguments,
    _flash_oncomplete,
    _flash_oncomplete_arguments,
    _scroll_oncomplete,
    _scroll_oncomplete_arguments,
    _shake_oncomplete,
    _shake_oncomplete_arguments,
    _tilt_oncomplete,
    _tilt_oncomplete_arguments,
    _zoom_oncomplete,
    _zoom_oncomplete_arguments,
    _is_scrolling,
    _is_tilting,
    _is_fading,
    _is_flashing,
    _is_zooming,
    _is_shaking,
    _is_resizing,
    _safe_area,
    _filters,
    _length
}


